version: "3.6"
services:
  webhook2mqtt:
    build: .
    restart: always
#    network_mode: "host"
    networks:
      - webhook2mqtt_default
# adapt to your needs
    ports:
      - "127.0.0.1:1357:1357"
      - "192.168.0.136:1357:1357"
    dns_search: lan
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
     TZ: "America/Toronto"
     MQTT_SERVER: '192.168.0.186'
     MQTT_PORT: 1883
     MQTT_USER: 'mqtt'
     MQTT_PASSWORD: 'D3u53414'
     MQTT_PATH: 'webhook/'
    logging:
      driver: syslog
    command: gunicorn -w 4 -b 0.0.0.0:1357 main:app
networks:
  webhook2mqtt_default:
    external: true
