name: Deploy Webhook2MQTT

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2  # Sets up Docker Buildx

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
        env:  # Pass secrets as environment variables
          MQTT_USER: ${{ secrets.MQTT_USER }}
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
          MQTT_HOST: ${{ secrets.MQTT_HOST }}
